# - Config syntax: https://github.com/Ezard/semantic-prs
# - If a repo has their own `semantic.yml` config file, that file will be used instead of this one.
#   - See https://github.com/Ezard/semantic-prs/issues/227 for more info.

# Validate the PR title, and ignore all commit messages
titleOnly: true